server:
  port: 7701

spring:
  application:
    name: producer

eureka:
  instance:
#    instance-id: producer-service-1
    lease-renewal-interval-in-seconds: 5 # 心跳间隔时间(默认30s)
    lease-expiration-duration-in-seconds: 3 # 最后一次收到心跳时等待时间，超时会移除client(默认90秒)
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8800/eureka
